import useDataTablePagination from '@/hooks/usePaginationState';
import { sortByIndonesianDate } from '@/utils/sortFunction';
import { PenBox } from 'lucide-react';
import { TableColumn } from 'react-data-table-component';
import Table from './Table';
import { Button } from './ui/button';

type DataRow = {
    id: number;
    namaPengusul: string;
    judulPenelitian: string;
    file: string;
    date: string;
};

const data: DataRow[] = [
    {
        id: 1,
        file: 'asd-file-1',
        judulPenelitian: 'Analisis Dampak Perubahan Iklim Terhadap Produksi Padi di Jawa Barat',
        namaPengusul: 'Dr. Budi Santoso',
        date: '20-September-2020',
    },
    {
        id: 2,
        file: 'asd-file-2',
        judulPenelitian: 'Pengembangan Algoritma Machine Learning untuk Prediksi Harga Saham',
        namaPengusul: 'Prof. Siti Rahayu',
        date: '15-Oktober-2020',
    },
    {
        id: 3,
        file: 'asd-file-3',
        judulPenelitian: 'Studi Komparatif Efektivitas Vaksin COVID-19 Berbagai Merek',
        namaPengusul: 'Ir. Ahmad Dhani',
        date: '01-November-2020',
    },
    {
        id: 4,
        file: 'asd-file-4',
        judulPenelitian: 'Penerapan Teknologi Blockchain dalam Sistem Pemilu Indonesia',
        namaPengusul: 'M.Sc. Rina Dewi',
        date: '10-Desember-2020',
    },
    {
        id: 5,
        file: 'asd-file-5',
        judulPenelitian: 'Eksplorasi Potensi Energi Terbarukan dari Sampah Organik Kota',
        namaPengusul: 'Dr. Eng. Heru Susanto',
        date: '05-Januari-2021',
    },
    {
        id: 6,
        file: 'asd-file-6',
        judulPenelitian: 'Kajian Filologi Naskah Kuno "Serat Centhini" dan Relevansinya',
        namaPengusul: 'Drs. Supriadi',
        date: '28-Februari-2021',
    },
    {
        id: 7,
        file: 'asd-file-7',
        judulPenelitian: 'Hubungan antara Pola Tidur dan Kinerja Akademik Mahasiswa',
        namaPengusul: 'Prof. Dr. Maya Sari',
        date: '17-Maret-2021',
    },
    {
        id: 8,
        file: 'asd-file-8',
        judulPenelitian: 'Inovasi Material Komposit Berbasis Serat Alam untuk Otomotif',
        namaPengusul: 'Ir. Joko Pramono',
        date: '03-April-2021',
    },
    {
        id: 9,
        file: 'asd-file-9',
        judulPenelitian: 'Analisis Spasial Persebaran Kasus Demam Berdarah di Jakarta',
        namaPengusul: 'Dr. Kartika Wijaya',
        date: '22-Mei-2021',
    },
    {
        id: 10,
        file: 'asd-file-10',
        judulPenelitian: 'Strategi Pemasaran Digital UMKM Terdampak Pandemi',
        namaPengusul: 'M.B.A. Faisal Amir',
        date: '12-Juni-2021',
    },
    {
        id: 11,
        file: 'asd-file-11',
        judulPenelitian: 'Pemanfaatan Teknologi Augmented Reality dalam Pembelajaran Sejarah',
        namaPengusul: 'Dr. Puspita Sari',
        date: '07-Juli-2021',
    },
    {
        id: 12,
        file: 'asd-file-12',
        judulPenelitian: 'Rancangan Sistem Keamanan Jaringan Berbasis Deep Learning',
        namaPengusul: 'Prof. Dr. Ir. Adi Nugroho',
        date: '25-Agustus-2021',
    },
    {
        id: 13,
        file: 'asd-file-13',
        judulPenelitian: 'Karakterisasi Senyawa Bioaktif dari Ekstrak Daun Kelor',
        namaPengusul: 'M.Farm. Apoteker Larasati',
        date: '19-September-2021',
    },
    {
        id: 14,
        file: 'asd-file-14',
        judulPenelitian: 'Model Prediksi Kualitas Udara Perkotaan Menggunakan Sensor IoT',
        namaPengusul: 'Ir. Sigit Prasetyo',
        date: '08-Oktober-2021',
    },
    {
        id: 15,
        file: 'asd-file-15',
        judulPenelitian: 'Evaluasi Kebijakan Subsidi Energi di Indonesia Periode 2015-2020',
        namaPengusul: 'Dr. Eko Widodo',
        date: '04-November-2021',
    },
    {
        id: 16,
        file: 'asd-file-16',
        judulPenelitian: 'Peran Komunitas Lokal dalam Konservasi Mangrove di Pesisir Utara Jawa',
        namaPengusul: 'Drs. Bambang Riyadi',
        date: '29-Desember-2021',
    },
    {
        id: 17,
        file: 'asd-file-17',
        judulPenelitian: 'Pengujian Prototipe Baterai Litium-Ion dengan Katoda Baru',
        namaPengusul: 'Dr. Eng. Retno Wulandari',
        date: '14-Januari-2022',
    },
    {
        id: 18,
        file: 'asd-file-18',
        judulPenelitian: 'Analisis Faktor yang Mempengaruhi Adopsi E-Wallet oleh Generasi Z',
        namaPengusul: 'M.M. Hendra Wijaya',
        date: '21-Februari-2022',
    },
    {
        id: 19,
        file: 'asd-file-19',
        judulPenelitian: 'Desain Sistem Irigasi Cerdas Berbasis Mikrokontroler',
        namaPengusul: 'Ir. Tania Permata',
        date: '10-Maret-2022',
    },
    {
        id: 20,
        file: 'asd-file-20',
        judulPenelitian: 'Kajian Estetika Arsitektur Rumah Tradisional Suku Baduy',
        namaPengusul: 'Prof. Dr. Seno Aji',
        date: '05-April-2022',
    },
    {
        id: 21,
        file: 'asd-file-21',
        judulPenelitian: 'Identifikasi Gen Penyebab Resistensi Antibiotik pada Bakteri E. Coli',
        namaPengusul: 'Dr. Biologi Risa Handayani',
        date: '28-Mei-2022',
    },
    {
        id: 22,
        file: 'asd-file-22',
        judulPenelitian: 'Model Matematis Penyebaran Hoaks di Media Sosial',
        namaPengusul: 'M.Kom. Bayu Segara',
        date: '17-Juni-2022',
    },
    {
        id: 23,
        file: 'asd-file-23',
        judulPenelitian: 'Pengaruh Stres Kerja terhadap Produktivitas Karyawan Perusahaan Startup',
        namaPengusul: 'Dra. Psikologi Erna Sulistyowati',
        date: '09-Juli-2022',
    },
    {
        id: 24,
        file: 'asd-file-24',
        judulPenelitian: 'Optimasi Proses Sintesis Nanopartikel Emas untuk Aplikasi Sensor',
        namaPengusul: 'Dr. Kimia Antonius Jaya',
        date: '03-Agustus-2022',
    },
    {
        id: 25,
        file: 'asd-file-25',
        judulPenelitian: 'Restorasi Ekosistem Terumbu Karang Menggunakan Metode Transplantasi',
        namaPengusul: 'Ir. Kelautan Dwi Cahyani',
        date: '21-September-2022',
    },
    {
        id: 26,
        file: 'asd-file-26',
        judulPenelitian: 'Pengaruh Inflasi dan Suku Bunga terhadap Nilai Tukar Rupiah',
        namaPengusul: 'M.E. Deni Ramadhan',
        date: '16-Oktober-2022',
    },
    {
        id: 27,
        file: 'asd-file-27',
        judulPenelitian: 'Perancangan Antarmuka Pengguna Aplikasi Mobile dengan Pendekatan UX/UI',
        namaPengusul: 'M.Des. Agung Laksono',
        date: '05-November-2022',
    },
    {
        id: 28,
        file: 'asd-file-28',
        judulPenelitian: 'Studi Etnobotani Tumbuhan Obat Tradisional Suku Dayak',
        namaPengusul: 'Dr. Botani Lestari Indah',
        date: '30-Desember-2022',
    },
    {
        id: 29,
        file: 'asd-file-29',
        judulPenelitian: 'Peningkatan Kualitas Citra Medis Menggunakan Teknik Denoising Adaptif',
        namaPengusul: 'Prof. Dr. Informatika Candra Wijaya',
        date: '18-Januari-2023',
    },
    {
        id: 30,
        file: 'asd-file-30',
        judulPenelitian: 'Pemodelan Perilaku Konsumen dalam E-Commerce di Masa Pandemi',
        namaPengusul: 'M.Si. Ekonomi Ratih Kusuma',
        date: '07-Februari-2023',
    },
    {
        id: 31,
        file: 'asd-file-31',
        judulPenelitian: 'Analisis Genomik Virus Dengue Tipe-2 di Wilayah Endemis',
        namaPengusul: 'Dr. Mikrobiologi Tania Sari',
        date: '02-Maret-2023',
    },
    {
        id: 32,
        file: 'asd-file-32',
        judulPenelitian: 'Pengembangan Kerangka Kerja Deep Learning untuk Pengenalan Suara Bahasa Lokal',
        namaPengusul: 'Ir. Komputer Jatmiko Susilo',
        date: '25-April-2023',
    },
    {
        id: 33,
        file: 'asd-file-33',
        judulPenelitian: 'Kajian Historis Peran Perempuan dalam Pergerakan Nasional Indonesia',
        namaPengusul: 'Prof. Dr. Sejarah Dewi Astuti',
        date: '14-Mei-2023',
    },
    {
        id: 34,
        file: 'asd-file-34',
        judulPenelitian: 'Desain Turbin Angin Skala Kecil untuk Pembangkit Listrik Rumah Tangga',
        namaPengusul: 'Dr. Teknik Mesin Bagus Wirawan',
        date: '08-Juni-2023',
    },
    {
        id: 35,
        file: 'asd-file-35',
        judulPenelitian: 'Eksperimen Penggunaan Limbah Plastik sebagai Bahan Tambahan Aspal',
        namaPengusul: 'M.T. Teknik Sipil Rendra Saputra',
        date: '01-Juli-2023',
    },
    {
        id: 36,
        file: 'asd-file-36',
        judulPenelitian: 'Analisis Sentimen Opini Publik terhadap Isu Lingkungan di Twitter',
        namaPengusul: 'Dr. Ilmu Komunikasi Mira Hadi',
        date: '20-Agustus-2023',
    },
    {
        id: 37,
        file: 'asd-file-37',
        judulPenelitian: 'Pengaruh Latihan Fisik Terhadap Keseimbangan Hormon Kortisol pada Atlet',
        namaPengusul: 'Prof. Dr. Kedokteran Olahraga Yoga Pratama',
        date: '11-September-2023',
    },
    {
        id: 38,
        file: 'asd-file-38',
        judulPenelitian: 'Implementasi Sistem Informasi Geografis (SIG) untuk Pemetaan Potensi Bencana',
        namaPengusul: 'Ir. Geodesi Sari Mulia',
        date: '04-Oktober-2023',
    },
    {
        id: 39,
        file: 'asd-file-39',
        judulPenelitian: 'Sintesis Senyawa Anti-Kanker dari Tumbuhan Laut Indonesia',
        namaPengusul: 'Dr. Biokimia Aditia Jaya',
        date: '29-November-2023',
    },
    {
        id: 40,
        file: 'asd-file-40',
        judulPenelitian: 'Analisis Efektivitas Kebijakan Moneter dalam Mengendalikan Inflasi',
        namaPengusul: 'M.Econ. Keuangan Puji Lestari',
        date: '15-Desember-2023',
    },
    {
        id: 41,
        file: 'asd-file-41',
        judulPenelitian: 'Penerapan Metode Agile dalam Pengembangan Perangkat Lunak Skala Besar',
        namaPengusul: 'Ir. Informatika Dedy Setiawan',
        date: '10-Januari-2024',
    },
    {
        id: 42,
        file: 'asd-file-42',
        judulPenelitian: 'Kajian Sosiologis Dampak Migrasi Tenaga Kerja pada Ketahanan Keluarga',
        namaPengusul: 'Drs. Sosiologi Wawan Kusuma',
        date: '23-Februari-2024',
    },
    {
        id: 43,
        file: 'asd-file-43',
        judulPenelitian: 'Pengembangan Pakan Ikan Berbasis Fermentasi Limbah Pertanian',
        namaPengusul: 'Dr. Perikanan Eko Prasetyo',
        date: '18-Maret-2024',
    },
    {
        id: 44,
        file: 'asd-file-44',
        judulPenelitian: 'Model Prediksi Keterlambatan Proyek Konstruksi Menggunakan Jaringan Saraf Tiruan',
        namaPengusul: 'Ir. Struktur Bangunan Rini Susanti',
        date: '04-April-2024',
    },
    {
        id: 45,
        file: 'asd-file-45',
        judulPenelitian: 'Analisis Faktor yang Mempengaruhi Loyalitas Pelanggan Platform Streaming Video',
        namaPengusul: 'M.Si. Manajemen Pemasaran Taufik Hidayat',
        date: '29-Mei-2024',
    },
    {
        id: 46,
        file: 'asd-file-46',
        judulPenelitian: 'Pengembangan Material Semikonduktor Organik untuk Sel Surya Fleksibel',
        namaPengusul: 'Prof. Dr. Fisika Nuklir Bambang Sutrisno',
        date: '16-Juni-2024',
    },
    {
        id: 47,
        file: 'asd-file-47',
        judulPenelitian: 'Penerapan Gamifikasi dalam Meningkatkan Motivasi Belajar Siswa SD',
        namaPengusul: 'Dr. Pendidikan Anak Usia Dini Maya Lestari',
        date: '03-Juli-2024',
    },
    {
        id: 48,
        file: 'asd-file-48',
        judulPenelitian: 'Sistem Deteksi Anomali pada Jaringan Listrik Pintar (Smart Grid)',
        namaPengusul: 'Ir. Listrik Tenaga Cepat Galih Prakoso',
        date: '28-Agustus-2024',
    },
    {
        id: 49,
        file: 'asd-file-49',
        judulPenelitian: 'Kajian Perubahan Penggunaan Lahan dan Dampaknya terhadap Banjir',
        namaPengusul: 'M.S. Geografi Bunga Citra',
        date: '14-September-2024',
    },
    {
        id: 50,
        file: 'asd-file-50',
        judulPenelitian: 'Model Kepemimpinan Transformasional dalam Organisasi Sektor Publik',
        namaPengusul: 'Dr. Administrasi Publik Ratna Wijaya',
        date: '09-Oktober-2024',
    },
    {
        id: 51,
        file: 'asd-file-51',
        judulPenelitian: 'Perancangan Sistem Pengendalian Kualitas Produk Otomatis Berbasis Visi Komputer',
        namaPengusul: 'Ir. Mekatronika Arifin Jaya',
        date: '04-November-2024',
    },
    {
        id: 52,
        file: 'asd-file-52',
        judulPenelitian: 'Analisis Efek Konsumsi Kafein Terhadap Daya Tahan Fisik Atlet Lari Jarak Jauh',
        namaPengusul: 'Prof. Dr. Gizi Masyarakat Siska Dewi',
        date: '29-Desember-2024',
    },
    {
        id: 53,
        file: 'asd-file-53',
        judulPenelitian: 'Implementasi Internet of Things (IoT) untuk Monitoring Kualitas Air Tambak Udang',
        namaPengusul: 'Ir. Budidaya Perairan Dika Pratama',
        date: '17-Januari-2025',
    },
    {
        id: 54,
        file: 'asd-file-54',
        judulPenelitian: 'Studi Perbandingan Metode Deteksi Kecurangan (Fraud Detection) pada Transaksi Bank',
        namaPengusul: 'M.Akun. Akuntansi Forensik Eka Nurhayati',
        date: '12-Februari-2025',
    },
    {
        id: 55,
        file: 'asd-file-55',
        judulPenelitian: 'Pengembangan Aplikasi Mobile untuk Panduan Wisata Berbasis Lokasi',
        namaPengusul: 'Dr. Pariwisata Agung Setiabudi',
        date: '06-Maret-2025',
    },
    {
        id: 56,
        file: 'asd-file-56',
        judulPenelitian: 'Kajian Potensi Bionanomaterial dari Limbah Kulit Udang',
        namaPengusul: 'Prof. Dr. Kimia Organik Tio Hartanto',
        date: '01-April-2025',
    },
    {
        id: 57,
        file: 'asd-file-57',
        judulPenelitian: 'Analisis Sentimen Publik terhadap Pelayanan Kesehatan BPJS',
        namaPengusul: 'M.Kes. Kesehatan Masyarakat Rina Puspita',
        date: '26-Mei-2025',
    },
    {
        id: 58,
        file: 'asd-file-58',
        judulPenelitian: 'Desain dan Implementasi Sistem Telemedisin untuk Daerah Terpencil',
        namaPengusul: 'Ir. Biomedis Heri Wijaya',
        date: '21-Juni-2025',
    },
    {
        id: 59,
        file: 'asd-file-59',
        judulPenelitian: 'Faktor-Faktor Penentu Keberhasilan Ekspor Produk Kerajinan Lokal',
        namaPengusul: 'Dr. Ekonomi Internasional Lita Paramita',
        date: '16-Juli-2025',
    },
    {
        id: 60,
        file: 'asd-file-60',
        judulPenelitian: 'Optimasi Desain Struktur Jembatan Tipe Box Girder dengan Metode Elemen Hingga',
        namaPengusul: 'Ir. Teknik Sipil Duta Maulana',
        date: '10-Agustus-2025',
    },
    {
        id: 61,
        file: 'asd-file-61',
        judulPenelitian: 'Pengembangan Sistem Pengenal Wajah Berbasis Deep Convolutional Neural Network',
        namaPengusul: 'Dr. Komputer Vision Bayu Adityo',
        date: '05-September-2025',
    },
    {
        id: 62,
        file: 'asd-file-62',
        judulPenelitian: 'Studi Literatur Mengenai Pengaruh Musik Klasik terhadap Daya Ingat',
        namaPengusul: 'Dra. Seni Musik Wulan Sari',
        date: '30-Oktober-2025',
    },
    {
        id: 63,
        file: 'asd-file-63',
        judulPenelitian: 'Kajian Penerapan Energi Panas Bumi sebagai Sumber Pembangkit Listrik di Sulawesi',
        namaPengusul: 'Ir. Geologi Panas Bumi Teguh Santoso',
        date: '25-November-2025',
    },
    {
        id: 64,
        file: 'asd-file-64',
        judulPenelitian: 'Model Prediksi Kebangkrutan Perusahaan Non-Keuangan di Bursa Efek Indonesia',
        namaPengusul: 'M.Fin. Analisis Keuangan Bima Sakti',
        date: '20-Desember-2025',
    },
    {
        id: 65,
        file: 'asd-file-65',
        judulPenelitian: 'Analisis Faktor yang Mempengaruhi Penggunaan Kendaraan Listrik di Indonesia',
        namaPengusul: 'Dr. Transportasi Riki Hidayat',
        date: '15-Januari-2026',
    },
    {
        id: 66,
        file: 'asd-file-66',
        judulPenelitian: 'Inovasi Metode Pengawetan Makanan Laut Menggunakan Ekstrak Tanaman Herbal',
        namaPengusul: 'Prof. Dr. Teknologi Pangan Dewi Kartika',
        date: '10-Februari-2026',
    },
    {
        id: 67,
        file: 'asd-file-67',
        judulPenelitian: 'Perancangan Sistem Rekomendasi E-Learning Berbasis Minat Belajar Pengguna',
        namaPengusul: 'M.Edu. Teknologi Pendidikan Gilang Ramadhan',
        date: '05-Maret-2026',
    },
    {
        id: 68,
        file: 'asd-file-68',
        judulPenelitian: 'Kajian Hukum Perlindungan Data Pribadi dalam Transaksi Digital',
        namaPengusul: 'Dr. Ilmu Hukum Aditya Pratama',
        date: '30-April-2026',
    },
    {
        id: 69,
        file: 'asd-file-69',
        judulPenelitian: 'Sintesis dan Karakterisasi Polimer Konduktif untuk Aplikasi Sel Bahan Bakar',
        namaPengusul: 'Ir. Kimia Material Titi Sari',
        date: '25-Mei-2026',
    },
    {
        id: 70,
        file: 'asd-file-70',
        judulPenelitian: 'Peran Media Sosial dalam Pembentukan Opini Politik di Kalangan Milenial',
        namaPengusul: 'Drs. Ilmu Politik Guntur Wijaya',
        date: '20-Juni-2026',
    },
    {
        id: 71,
        file: 'asd-file-71',
        judulPenelitian: 'Optimasi Penjadwalan Produksi pada Industri Manufaktur dengan Algoritma Genetika',
        namaPengusul: 'Dr. Teknik Industri Riko Susanto',
        date: '15-Juli-2026',
    },
    {
        id: 72,
        file: 'asd-file-72',
        judulPenelitian: 'Analisis Faktor Risiko Kejadian Stunting pada Balita di Pedesaan',
        namaPengusul: 'M.P.H. Epidemiologi Dina Lestari',
        date: '10-Agustus-2026',
    },
    {
        id: 73,
        file: 'asd-file-73',
        judulPenelitian: 'Pengembangan Model Prediksi Potensi Erupsi Gunung Berapi Menggunakan Data Satelit',
        namaPengusul: 'Ir. Geofisika Indra Maulana',
        date: '05-September-2026',
    },
    {
        id: 74,
        file: 'asd-file-74',
        judulPenelitian: 'Kajian Perbandingan Sistem Perpajakan di Negara-Negara ASEAN',
        namaPengusul: 'Dr. Ilmu Ekonomi Pajak Aris Prabowo',
        date: '30-Oktober-2026',
    },
    {
        id: 75,
        file: 'asd-file-75',
        judulPenelitian: 'Penerapan Metode Fuzzy Logic dalam Sistem Pengambilan Keputusan Pertanian Cerdas',
        namaPengusul: 'M.T. Sistem Kendali Hani Fauziah',
        date: '25-November-2026',
    },
    {
        id: 76,
        file: 'asd-file-76',
        judulPenelitian: 'Analisis Kualitas Akustik Ruang Konser dengan Simulasi Komputer',
        namaPengusul: 'Dr. Arsitektur Akustik Wisnu Murti',
        date: '20-Desember-2026',
    },
    {
        id: 77,
        file: 'asd-file-77',
        judulPenelitian: 'Pengaruh Budaya Organisasi terhadap Kinerja Inovasi Perusahaan BUMN',
        namaPengusul: 'M.A. Manajemen SDM Dewi Anggraini',
        date: '15-Januari-2027',
    },
    {
        id: 78,
        file: 'asd-file-78',
        judulPenelitian: 'Pengembangan Pembangkit Listrik Tenaga Mikrohidro Portable',
        namaPengusul: 'Ir. Teknik Hidro Erwan Syahputra',
        date: '10-Februari-2027',
    },
    {
        id: 79,
        file: 'asd-file-79',
        judulPenelitian: 'Studi Karakteristik Mekanik dan Termal dari Paduan Logam Ringan',
        namaPengusul: 'Prof. Dr. Metalurgi Budi Darmawan',
        date: '05-Maret-2027',
    },
    {
        id: 80,
        file: 'asd-file-80',
        judulPenelitian: 'Analisis Kebutuhan Pelatihan Berbasis Kompetensi di Sektor Pariwisata',
        namaPengusul: 'Dr. Psikologi Industri Rita Purnama',
        date: '30-April-2027',
    },
    {
        id: 81,
        file: 'asd-file-81',
        judulPenelitian: 'Perancangan Model Simulasi Antrian Layanan Publik dengan Metode Monte Carlo',
        namaPengusul: 'M.T. Riset Operasi Dedi Santoso',
        date: '25-Mei-2027',
    },
    {
        id: 82,
        file: 'asd-file-82',
        judulPenelitian: 'Kajian Ekologi Hutan Mangrove dan Keanekaragaman Hayati Fauna',
        namaPengusul: 'Dr. Konservasi Alam Lina Wijayanti',
        date: '20-Juni-2027',
    },
    {
        id: 83,
        file: 'asd-file-83',
        judulPenelitian: 'Pengembangan Sistem Pengawasan Lalu Lintas Berbasis Sensor dan Kecerdasan Buatan',
        namaPengusul: 'Ir. Transportasi Cerdas Arya Nugraha',
        date: '15-Juli-2027',
    },
    {
        id: 84,
        file: 'asd-file-84',
        judulPenelitian: 'Analisis Faktor yang Mempengaruhi Keputusan Pembelian Properti Residensial',
        namaPengusul: 'M.Sc. Ekonomi Properti Fajar Alamsyah',
        date: '10-Agustus-2027',
    },
    {
        id: 85,
        file: 'asd-file-85',
        judulPenelitian: 'Inovasi Kemasan Makanan Ramah Lingkungan Berbasis Bioplastik',
        namaPengusul: 'Dr. Teknologi Pangan Rina Handayani',
        date: '05-September-2027',
    },
    {
        id: 86,
        file: 'asd-file-86',
        judulPenelitian: 'Studi Mengenai Efektivitas Terapi Musik untuk Pasien Depresi',
        namaPengusul: 'Dra. Psikologi Klinis Lisa Amelia',
        date: '30-Oktober-2027',
    },
    {
        id: 87,
        file: 'asd-file-87',
        judulPenelitian: 'Pengembangan Model Prediksi Curah Hujan Jangka Pendek Menggunakan Data Radar',
        namaPengusul: 'Ir. Meteorologi Gema Buana',
        date: '25-November-2027',
    },
    {
        id: 88,
        file: 'asd-file-88',
        judulPenelitian: 'Analisis Risiko Investasi Cryptocurrency di Pasar Indonesia',
        namaPengusul: 'M.B.A. Manajemen Risiko Tito Wardhana',
        date: '20-Desember-2027',
    },
    {
        id: 89,
        file: 'asd-file-89',
        judulPenelitian: 'Penerapan Teknologi Virtual Reality dalam Pelatihan Keterampilan Bedah',
        namaPengusul: 'Dr. Kedokteran Bedah Sari Utami',
        date: '15-Januari-2028',
    },
    {
        id: 90,
        file: 'asd-file-90',
        judulPenelitian: 'Kajian Filosifi di Balik Motif Batik Tradisional Nusantara',
        namaPengusul: 'Prof. Dr. Antropologi Budaya Sinta Raharjo',
        date: '10-Februari-2028',
    },
    {
        id: 91,
        file: 'asd-file-91',
        judulPenelitian: 'Desain Sistem Pembangkit Listrik Tenaga Surya Terapung di Waduk',
        namaPengusul: 'Ir. Teknik Energi Terbarukan Bayu Kurniawan',
        date: '05-Maret-2028',
    },
    {
        id: 92,
        file: 'asd-file-92',
        judulPenelitian: 'Analisis Kinerja Keuangan Bank Syariah dan Bank Konvensional',
        namaPengusul: 'M.E. Keuangan Syariah Dina Mariana',
        date: '30-April-2028',
    },
    {
        id: 93,
        file: 'asd-file-93',
        judulPenelitian: 'Pengembangan Alat Deteksi Dini Kebakaran Hutan Berbasis Sensor Nirkabel',
        namaPengusul: 'Dr. Teknik Elektro Iwan Dharmawan',
        date: '25-Mei-2028',
    },
    {
        id: 94,
        file: 'asd-file-94',
        judulPenelitian: 'Studi Peran Lembaga Adat dalam Pengelolaan Sumber Daya Alam',
        namaPengusul: 'Drs. Pembangunan Sosial Ardi Wicaksono',
        date: '20-Juni-2028',
    },
    {
        id: 95,
        file: 'asd-file-95',
        judulPenelitian: 'Optimasi Proses Produksi Bioetanol dari Limbah Tebu',
        namaPengusul: 'Ir. Bioproses Laksmi Dewi',
        date: '15-Juli-2028',
    },
    {
        id: 96,
        file: 'asd-file-96',
        judulPenelitian: 'Analisis Dampak Penggunaan Gadget Terhadap Kesehatan Mental Remaja',
        namaPengusul: 'Dr. Kesehatan Remaja Puspita Rini',
        date: '10-Agustus-2028',
    },
    {
        id: 97,
        file: 'asd-file-97',
        judulPenelitian: 'Implementasi Algoritma Steganografi untuk Keamanan Data Digital',
        namaPengusul: 'M.Kom. Keamanan Informasi Rudi Santoso',
        date: '05-September-2028',
    },
    {
        id: 98,
        file: 'asd-file-98',
        judulPenelitian: 'Kajian Perbandingan Sistem Pendidikan Vokasi di Indonesia dan Jerman',
        namaPengusul: 'Dr. Pendidikan Vokasi Tono Hartono',
        date: '30-Oktober-2028',
    },
    {
        id: 99,
        file: 'asd-file-99',
        judulPenelitian: 'Pengembangan Robot Laba-Laba untuk Inspeksi Area Berbahaya',
        namaPengusul: 'Ir. Robotika Sinta Dewi',
        date: '25-November-2028',
    },
    {
        id: 100,
        file: 'asd-file-100',
        judulPenelitian: 'Analisis Potensi Ekonomi Kreatif Berbasis Budaya Lokal di Yogyakarta',
        namaPengusul: 'Prof. Dr. Ekonomi Kreatif Haris Wijaya',
        date: '20-Desember-2028',
    },
];

export default function DataReviewUsulanPengabmas() {
    const { currentPage, perPage, handlePageChange, handlePerRowsChange } = useDataTablePagination(20);

    const columns: TableColumn<DataRow>[] = [
        {
            name: 'No',
            // selector: (_, rowIndex) => (rowIndex ? rowIndex + 1 : 1),
            cell: (row, index) => (currentPage - 1) * perPage + index + 1,
            width: '2rem',
            style: {
                padding: '0px',
                justifyContent: 'center',
            },
        },
        {
            name: 'Judul Penelitian',
            selector: (row) => row.judulPenelitian,
            sortable: true,
            wrap: true,
        },
        {
            name: 'Nama Pengusul',
            selector: (row) => row.namaPengusul,
            sortable: true,
        },
        {
            name: 'File',
            selector: (row) => row.file,
            sortable: true,
        },
        {
            name: 'Tanggal Usulan',
            selector: (row) => row.date,
            sortable: true,
            sortFunction: (rowA, rowB) => sortByIndonesianDate(rowA, rowB, 'date'),
        },
        {
            name: 'Aksi',
            cell: () => (
                <div>
                    <Button className="cursor-pointer bg-blue-600 hover:bg-blue-400">
                        <PenBox></PenBox> Beri Tanggapan
                    </Button>
                </div>
            ),
        },
    ];

    return (
        <div className="space-y-4 p-4">
            <h2 className="text-xl font-semibold">DATA PLOTING REVIEW PENGABDIAN MASYARAKAT</h2>
            <Table columns={columns} data={data} handlePageChange={handlePageChange} handlePerRowsChange={handlePerRowsChange} />
        </div>
    );
}
