import useDataTablePagination from '@/hooks/usePaginationState';
import { sortByIndonesianDate } from '@/utils/sortFunction';
import { TableColumn } from 'react-data-table-component';
import Table from './Table';

type DataRowHasilReviewPenelitian = {
    id: number;
    namaPengusul: string;
    judulPenelitian: string;
    reviewer1: string;
    reviewer2: string;
    fileKomentar: string;
    tanggapan: string;
    nilai: string;
    jenisLaporan: string;
    tanggal: string;
};

export default function HasilReviewPenelitian() {
    const data: DataRowHasilReviewPenelitian[] = [
        {
            id: 1,
            namaPengusul: 'Dr. Wibowo Jati',
            judulPenelitian: 'Pengembangan Sistem Informasi Akademik Terpadu',
            reviewer1: 'Prof. Budi Setiawan',
            reviewer2: 'Dr. Rina Puspita Sari',
            fileKomentar: 'Komentar_Wibowo_R1_Final.pdf',
            tanggapan: 'Revisi minor telah dipenuhi. Konsensus kedua reviewer: Lanjutkan.',
            nilai: 'A',
            jenisLaporan: 'Proposal',
            tanggal: '20-Oktober-2024',
        },
        {
            id: 2,
            namaPengusul: 'Prof. Siti Fatimah',
            judulPenelitian: 'Analisis Kualitas Air Minum Perkotaan Menggunakan Sensor IoT',
            reviewer1: 'Ir. Citra Dewi, M.T.',
            reviewer2: 'Dr. Taufik Hidayat, M.P.',
            fileKomentar: 'Komentar_Siti_R2_Revisi.pdf',
            tanggapan: 'Revisi mayor (validasi sensor) diterima. Disetujui dengan perbaikan akhir.',
            nilai: 'B+',
            jenisLaporan: 'Proposal',
            tanggal: '25-Oktober-2024',
        },
        {
            id: 3,
            namaPengusul: 'Ir. Budi Santoso',
            judulPenelitian: 'Efektivitas Model Pembelajaran Berbasis Proyek (PBL) pada SMK',
            reviewer1: 'Andi Pratama, M.A.',
            reviewer2: 'Zulfa Hanum, M.Pd.',
            fileKomentar: 'Komentar_Budi_R3_Final.docx',
            tanggapan: 'Semua masukan (terutama tentang PBL jangka panjang) telah diintegrasikan. Lolos.',
            nilai: 'A-',
            jenisLaporan: 'Proposal',
            tanggal: '01-November-2024',
        },
        {
            id: 4,
            namaPengusul: 'Dra. Dewi Anggraini',
            judulPenelitian: 'Perancangan Sistem Pakar Diagnosa Penyakit Tropis dengan Metode Fuzzy',
            reviewer1: 'Dr. Farida Hasan',
            reviewer2: 'Sari Mulia, M.Kom., Ph.D.',
            fileKomentar: 'Komentar_Dewi_R4_Revisi.pdf',
            tanggapan: 'Integrasi studi kasus tambahan meningkatkan bobot riset. Disetujui.',
            nilai: 'A',
            jenisLaporan: 'Proposal',
            tanggal: '05-November-2024',
        },
        {
            id: 5,
            namaPengusul: 'Dr. Agung Pramono',
            judulPenelitian: 'Kajian Dampak Pembangunan Jalan Tol Terhadap Ekonomi Lokal',
            reviewer1: 'Prof. Herman Jaya',
            reviewer2: 'Xena Amelia, M.E.',
            fileKomentar: 'Komentar_Agung_R5_Final.pdf',
            tanggapan: 'Relevansi tinggi. Hasil konsensus: Sangat layak didanai (A+).',
            nilai: 'A+',
            jenisLaporan: 'Proposal',
            tanggal: '10-November-2024',
        },
        {
            id: 6,
            namaPengusul: 'Prof. Dr. Fitriani',
            judulPenelitian: 'Sintesis Nanomaterial Karbon untuk Aplikasi Baterai Lithium-Ion',
            reviewer1: 'Prof. Rudi Hartono',
            reviewer2: 'Iwan Darmawan, S.T., M.T.',
            fileKomentar: 'Komentar_Fitriani_RK_Rev.pdf',
            tanggapan: 'Telah dilampirkan data SEM-EDX dan hasil TGA. Kemajuan sesuai jadwal.',
            nilai: 'A',
            jenisLaporan: 'Laporan Kemajuan',
            tanggal: '15-Mei-2025',
        },
        {
            id: 7,
            namaPengusul: 'Joko Susilo, M.Kom.',
            judulPenelitian: 'Penerapan Data Mining untuk Prediksi Tingkat Kepuasan Pelanggan',
            reviewer1: 'Dr. Joko Susilo, M.Kom.',
            reviewer2: 'Lukman Hakim, M.Kom.',
            fileKomentar: 'Komentar_Joko_RK_Rev.docx',
            tanggapan: 'Penambahan analisis perbandingan algoritma telah memperkuat hasil. Lanjutkan.',
            nilai: 'B',
            jenisLaporan: 'Laporan Kemajuan',
            tanggal: '20-Mei-2025',
        },
        {
            id: 8,
            namaPengusul: 'Rini Wahyuni, S.T.',
            judulPenelitian: 'Optimalisasi Desain Turbin Air Pico Hydro Skala Rumah Tangga',
            reviewer1: 'Oscar Darmawan, M.A.',
            reviewer2: 'Rudi Nugroho, S.T.',
            fileKomentar: 'Komentar_Rini_RK_Final.pdf',
            tanggapan: 'Simulasi CFD terlampir. Desain final disetujui untuk manufaktur purwarupa.',
            nilai: 'A-',
            jenisLaporan: 'Laporan Kemajuan',
            tanggal: '25-Mei-2025',
        },
        {
            id: 9,
            namaPengusul: 'Anton Setiawan, Ph.D.',
            judulPenelitian: 'Studi Komparatif Implementasi Merdeka Belajar di Perguruan Tinggi Swasta',
            reviewer1: 'Prof. Vino Adrianto',
            reviewer2: 'Wulan Febriani, M.Hum.',
            fileKomentar: 'Komentar_Anton_RK_Rev.pdf',
            tanggapan: 'Pembahasan kualitatif sudah diperdalam. Progress sesuai rencana.',
            nilai: 'B+',
            jenisLaporan: 'Laporan Kemajuan',
            tanggal: '01-Juni-2025',
        },
        {
            id: 10,
            namaPengusul: 'Maya Sari, S.E., M.Si.',
            judulPenelitian: 'Analisis Faktor yang Mempengaruhi Adopsi Fintech pada Generasi Milenial',
            reviewer1: 'Mega Puspita, M.Ak.',
            reviewer2: 'Eka Wijaya, S.E., M.Si.',
            fileKomentar: 'Komentar_Maya_RK_Final.docx',
            tanggapan: 'Saran kebijakan telah dikembangkan. Lanjutkan ke penulisan draf jurnal.',
            nilai: 'A',
            jenisLaporan: 'Laporan Kemajuan',
            tanggal: '05-Juni-2025',
        },
        {
            id: 11,
            namaPengusul: 'Rizal Hakim, S.Kom.',
            judulPenelitian: 'Pengembangan Aplikasi Mobile untuk Layanan Kesehatan Primer',
            reviewer1: 'Dr. Rina Puspita Sari',
            reviewer2: 'Yoga Pratama, S.Kom.',
            fileKomentar: 'Komentar_Rizal_LA_Final.pdf',
            tanggapan: 'Uji UX memuaskan. Luaran berupa source code dan jurnal telah lengkap. Selesai.',
            nilai: 'A-',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '10-Desember-2025',
        },
        {
            id: 12,
            namaPengusul: 'Citra Kirana, M.Eng.',
            judulPenelitian: 'Peningkatan Efisiensi Pembangkit Listrik Tenaga Surya Hibrid',
            reviewer1: 'Ir. Citra Dewi, M.T.',
            reviewer2: 'Iwan Darmawan, S.T., M.T.',
            fileKomentar: 'Komentar_Citra_LA_Final.pdf',
            tanggapan: 'Efisiensi sangat tinggi, potensi paten terkonfirmasi. Selesai.',
            nilai: 'A+',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '15-Desember-2025',
        },
        {
            id: 13,
            namaPengusul: 'Eka Wijaya, S.Pd.',
            judulPenelitian: 'Integrasi Nilai Pancasila dalam Pengembangan Kurikulum Digital',
            reviewer1: 'Andi Pratama, M.A.',
            reviewer2: 'Umi Kalsum, M.Ag.',
            fileKomentar: 'Komentar_Eka_LA_Final.docx',
            tanggapan: 'Modul sudah terimplementasi. Laporan memenuhi kriteria. Selesai.',
            nilai: 'A',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '20-Desember-2025',
        },
        {
            id: 14,
            namaPengusul: 'Yoga Pratama, M.T.',
            judulPenelitian: 'Implementasi Internet of Things (IoT) untuk Sistem Irigasi Cerdas',
            reviewer1: 'Rudi Nugroho, S.T.',
            reviewer2: 'Joko Susilo, M.Kom.',
            fileKomentar: 'Komentar_Yoga_LA_Rev.pdf',
            tanggapan: 'Dokumentasi publikasi diperbaiki dan dilampirkan. Disetujui (Revisi Selesai).',
            nilai: 'B',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '25-Desember-2025',
        },
        {
            id: 15,
            namaPengusul: 'Fina Az Zahra, S.Sos.',
            judulPenelitian: 'Analisis Peran Media Sosial dalam Pembentukan Opini Publik Lokal',
            reviewer1: 'Hesti Lestari, M.I.Kom.',
            reviewer2: 'Eka Wijaya, S.E., M.Si.',
            fileKomentar: 'Komentar_Fina_LA_Rev.docx',
            tanggapan: 'Poin spesifik dampak media sosial sudah ditambahkan. Disetujui.',
            nilai: 'B-',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '01-Januari-2026',
        },
        {
            id: 16,
            namaPengusul: 'Gita Lestari, M.Psi.',
            judulPenelitian: 'Pengembangan Alat Ukur Kepuasan Kerja Dosen Berbasis Budaya Organisasi',
            reviewer1: 'Puspa Sari, M.Psi.',
            reviewer2: 'Bela Safitri, S.Psi.',
            fileKomentar: 'Komentar_Gita_LA_Final.pdf',
            tanggapan: 'Alat ukur telah terpublikasi. Laporan sangat baik. Selesai.',
            nilai: 'A',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '05-Januari-2026',
        },
        {
            id: 17,
            namaPengusul: 'Hendra Kusuma, S.H.',
            judulPenelitian: 'Kajian Hukum Pidana terkait Kejahatan Siber di Indonesia',
            reviewer1: 'Qiran Maulana, S.H., M.H.',
            reviewer2: 'Prof. Herman Jaya',
            fileKomentar: 'Komentar_Hendra_LA_Final.pdf',
            tanggapan: 'Rekomendasi kebijakan siap diserahkan ke instansi terkait. Selesai.',
            nilai: 'A+',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '10-Januari-2026',
        },
        {
            id: 18,
            namaPengusul: 'Irma Suryani, M.Sc.',
            judulPenelitian: 'Inovasi Pakan Ternak Berbasis Fermentasi Limbah Pertanian',
            reviewer1: 'Dr. Ganjar Pranowo',
            reviewer2: 'Taufik Hidayat, S.P., M.P.',
            fileKomentar: 'Komentar_Irma_LA_Final.docx',
            tanggapan: 'Proses paten berjalan lancar. Hasil penelitian berdampak luas. Selesai.',
            nilai: 'A+',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '15-Januari-2026',
        },
        {
            id: 19,
            namaPengusul: 'Kiki Maulana, S.Ked.',
            judulPenelitian: 'Pengaruh Senam Aerobik terhadap Kualitas Tidur Lansia di Panti Jompo',
            reviewer1: 'Prof. Lukman Hakim',
            reviewer2: 'Dr. Kartika Sari, M.Gizi.',
            fileKomentar: 'Komentar_Kiki_LA_Final.pdf',
            tanggapan: 'Laporan klinis tuntas. Disetujui untuk publikasi ilmiah. Selesai.',
            nilai: 'A',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '20-Januari-2026',
        },
        {
            id: 20,
            namaPengusul: 'Linda Herawati, S.T.',
            judulPenelitian: 'Pengembangan Purwarupa Sistem Peringatan Dini Kebakaran Hutan',
            reviewer1: 'Ir. Citra Dewi, M.T.',
            reviewer2: 'Dr. Ari Wibowo',
            fileKomentar: 'Komentar_Linda_LA_Final.pdf',
            tanggapan: 'Purwarupa teruji di lapangan. Laporan administratif lengkap. Selesai.',
            nilai: 'A-',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '25-Januari-2026',
        },
        {
            id: 21,
            namaPengusul: 'Marwan Effendi, M.Pd.',
            judulPenelitian: 'Penerapan Metode Gamifikasi dalam Peningkatan Hasil Belajar Geografi',
            reviewer1: 'Zulfa Hanum, M.Pd.',
            reviewer2: 'Andi Pratama, M.A.',
            fileKomentar: 'Komentar_Marwan_R21_Final.docx',
            tanggapan: 'Revisi bab 4 diselesaikan. Disetujui untuk didanai.',
            nilai: 'B+',
            jenisLaporan: 'Proposal',
            tanggal: '01-Maret-2025',
        },
        {
            id: 22,
            namaPengusul: 'Nia Kurnia, M.Kom.',
            judulPenelitian: 'Klasifikasi Citra Satelit Resolusi Tinggi Menggunakan Deep Learning',
            reviewer1: 'Sari Mulia, M.Kom., Ph.D.',
            reviewer2: 'Dr. Rina Puspita Sari',
            fileKomentar: 'Komentar_Nia_RK_Final.pdf',
            tanggapan: 'Akurasi model Deep Learning sangat baik. Laporan kemajuan disetujui.',
            nilai: 'A',
            jenisLaporan: 'Laporan Kemajuan',
            tanggal: '10-Agustus-2025',
        },
        {
            id: 23,
            namaPengusul: 'Oka Dharmawan, S.E.',
            judulPenelitian: 'Studi Kelayakan Investasi Proyek Infrastruktur Berkelanjutan',
            reviewer1: 'Xena Amelia, M.E.',
            reviewer2: 'Mega Puspita, M.Ak.',
            fileKomentar: 'Komentar_Oka_R23_Final.docx',
            tanggapan: 'Proyeksi keuangan disesuaikan. Proposal layak dilanjutkan.',
            nilai: 'B',
            jenisLaporan: 'Proposal',
            tanggal: '15-Maret-2025',
        },
        {
            id: 24,
            namaPengusul: 'Putri Amelia, S.IP.',
            judulPenelitian: 'Analisis Kebijakan Pengelolaan Sampah Zero Waste di Tingkat Desa',
            reviewer1: 'Oscar Darmawan, M.A.',
            reviewer2: 'Hesti Lestari, M.I.Kom.',
            fileKomentar: 'Komentar_Putri_RK_Final.pdf',
            tanggapan: 'Rekomendasi kebijakan diperjelas. Kemajuan sesuai target.',
            nilai: 'A-',
            jenisLaporan: 'Laporan Kemajuan',
            tanggal: '20-Agustus-2025',
        },
        {
            id: 25,
            namaPengusul: 'Quincy Rian, M.Hum.',
            judulPenelitian: 'Kajian Filologi Naskah Kuno Sastra Melayu dan Nilai Budaya Lokal',
            reviewer1: 'Wulan Febriani, M.Hum.',
            reviewer2: 'Prof. Vino Adrianto',
            fileKomentar: 'Komentar_Quincy_LA_Final.docx',
            tanggapan: 'Tinjauan budaya tuntas. Laporan diterima sebagai luaran buku.',
            nilai: 'A',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '15-Februari-2026',
        },
        {
            id: 26,
            namaPengusul: 'Rudi Hartono, S.T.',
            judulPenelitian: 'Perancangan Sistem Pengendali Kendaraan Otonom Skala Mini',
            reviewer1: 'Iwan Darmawan, S.T., M.T.',
            reviewer2: 'Rudi Nugroho, S.T.',
            fileKomentar: 'Komentar_Rudi_R26_Rev.pdf',
            tanggapan: 'Algoritma *path planning* diperbaiki. Proposal disetujui.',
            nilai: 'B+',
            jenisLaporan: 'Proposal',
            tanggal: '20-Maret-2025',
        },
        {
            id: 27,
            namaPengusul: 'Sari Mulia, M.Farm.',
            judulPenelitian: 'Uji Toksisitas dan Aktivitas Anti-Kanker Ekstrak Tanaman Herbal X',
            reviewer1: 'Dr. Kartika Sari, M.Gizi.',
            reviewer2: 'Fina Az Zahra, M.Farm.',
            fileKomentar: 'Komentar_Sari_RK_Final.pdf',
            tanggapan: 'Uji *in vivo* telah direncanakan dengan baik. Progress sangat memuaskan.',
            nilai: 'A+',
            jenisLaporan: 'Laporan Kemajuan',
            tanggal: '25-Agustus-2025',
        },
        {
            id: 28,
            namaPengusul: 'Taufik Hidayat, M.Si.',
            judulPenelitian: 'Pemodelan Spasial Distribusi Sumber Daya Air Permukaan',
            reviewer1: 'Dr. Ari Wibowo',
            reviewer2: 'Joko Susilo, M.Kom.',
            fileKomentar: 'Komentar_Taufik_LA_Final.docx',
            tanggapan: 'Peta risiko kekeringan dilampirkan. Laporan akhir diterima.',
            nilai: 'A-',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '01-Maret-2026',
        },
        {
            id: 29,
            namaPengusul: 'Umi Kalsum, S.Ag.',
            judulPenelitian: 'Peran Lembaga Keagamaan dalam Peningkatan Kesejahteraan Sosial',
            reviewer1: 'Umi Kalsum, M.Ag.',
            reviewer2: 'Qiran Maulana, S.H., M.H.',
            fileKomentar: 'Komentar_Umi_LA_Final.pdf',
            tanggapan: 'Laporan diterima. Luaran berupa panduan pemberdayaan masyarakat selesai.',
            nilai: 'A',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '05-Maret-2026',
        },
        {
            id: 30,
            namaPengusul: 'Vino Adrianto, S.Sn.',
            judulPenelitian: 'Eksplorasi Teknik Visualisasi Data dalam Seni Rupa Kontemporer',
            reviewer1: 'Prof. Vino Adrianto',
            reviewer2: 'Deni Susanto, M.Ds.',
            fileKomentar: 'Komentar_Vino_LA_Final.docx',
            tanggapan: 'Karya seni rupa dan laporan tuntas. Disetujui sebagai luaran HKI/Seni.',
            nilai: 'A+',
            jenisLaporan: 'Laporan Akhir',
            tanggal: '10-Maret-2026',
        },
    ];

    const { currentPage, perPage, handlePageChange, handlePerRowsChange } = useDataTablePagination(20);

    const columns: TableColumn<DataRowHasilReviewPenelitian>[] = [
        {
            name: 'No',
            cell: (row, index) => (currentPage - 1) * perPage + index + 1,
            width: '2rem',
            style: {
                padding: '0px',
                justifyContent: 'center',
            },
        },
        {
            name: 'Pengusul',
            selector: (row) => row.namaPengusul,
            sortable: true,
            wrap: true,
        },
        {
            name: 'Judul Penelitian',
            selector: (row) => row.judulPenelitian,
            sortable: true,
            wrap: true,
        },
        {
            name: 'Reviewer',
            // selector: (row) => row.reviewer,
            cell: (row) => (
                <div className="w-full space-y-2">
                    <div className="flex">
                        {/* <p className="w-3/10">Reviewer 1</p> */}
                        <p>{row.reviewer1}</p>
                    </div>
                    <div className="flex">
                        {/* <p className="w-3/10">Reviewer 2</p> */}
                        <p>{row.reviewer2}</p>
                    </div>
                </div>
            ),
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'File Komentar',
            selector: (row) => row.fileKomentar,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Tanggapan',
            selector: (row) => row.tanggapan,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Nilai',
            selector: (row) => row.nilai,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Jenis Laporan',
            selector: (row) => row.jenisLaporan,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Tanggal',
            selector: (row) => row.tanggal,
            sortable: true,
            sortFunction: (rowA, rowB) => sortByIndonesianDate(rowA, rowB, 'tanggal'),
            wrap: true,
            center: true,
        },
    ];

    return (
        <div className="rounded-lg bg-white p-6 shadow">
            <h2 className="mb-2 text-xl font-semibold">Daftar Review Penelitian</h2>
            <Table columns={columns} data={data} handlePageChange={handlePageChange} handlePerRowsChange={handlePerRowsChange} />
        </div>
    );
}
