import Table from '@/components/Table';
import { Button } from '@/components/ui/button';
import useDataTablePagination from '@/hooks/usePaginationState';
import DashLayout from '@/layouts/dash-layout';
import { Head } from '@inertiajs/react';
import { PenBox, Trash2 } from 'lucide-react';
import { TableColumn } from 'react-data-table-component';

type DataRowReviewer = {
    id: number;
    foto: string;
    nik: string;
    nama: string;
    email: string;
    noHp: string;
    jafung: string;
    intitusi: string;
    fakultas: string;
    prodi: string;
    username: string;
    password: string;
};

export default function DataReviewerPage() {
    const data: DataRowReviewer[] = [
        {
            id: 1,
            foto: 'https://placehold.co/600x400?text=R01',
            nik: '197003012000031001',
            nama: 'Dr. Rina Puspita Sari',
            email: 'rina.puspita@univ-a.ac.id',
            noHp: '081234567801',
            jafung: 'Lektor Kepala',
            intitusi: 'Universitas Airlangga',
            fakultas: 'Fakultas Sains dan Teknologi',
            prodi: 'Teknik Informatika',
            username: 'rina_ps',
            password: 'pass@Rina01',
        },
        {
            id: 2,
            foto: 'https://placehold.co/600x400?text=R02',
            nik: '198510202010122005',
            nama: 'Prof. Budi Setiawan, Ph.D.',
            email: 'budi.setiawan@itb.ac.id',
            noHp: '081234567802',
            jafung: 'Guru Besar',
            intitusi: 'Institut Teknologi Bandung',
            fakultas: 'Fakultas Teknik Sipil dan Lingkungan',
            prodi: 'Teknik Lingkungan',
            username: 'budi_st',
            password: 'pass@Budi02',
        },
        {
            id: 3,
            foto: 'https://placehold.co/600x400?text=R03',
            nik: '197805122005011003',
            nama: 'Ir. Citra Dewi, M.T.',
            email: 'citra.dewi@ugm.ac.id',
            noHp: '081234567803',
            jafung: 'Lektor',
            intitusi: 'Universitas Gadjah Mada',
            fakultas: 'Fakultas Teknik',
            prodi: 'Teknik Elektro',
            username: 'citra_dw',
            password: 'pass@Citra03',
        },
        {
            id: 4,
            foto: 'https://placehold.co/600x400?text=R04',
            nik: '199001012015022010',
            nama: 'Andi Pratama, S.Pd., M.A.',
            email: 'andi.pratama@upi.edu',
            noHp: '081234567804',
            jafung: 'Asisten Ahli',
            intitusi: 'Universitas Pendidikan Indonesia',
            fakultas: 'Fakultas Ilmu Pendidikan',
            prodi: 'Pendidikan Bahasa Inggris',
            username: 'andi_pt',
            password: 'pass@Andi04',
        },
        {
            id: 5,
            foto: 'https://placehold.co/600x400?text=R05',
            nik: '196511251995061007',
            nama: 'Prof. Herman Jaya, Ph.D.',
            email: 'herman.jaya@ui.ac.id',
            noHp: '081234567805',
            jafung: 'Guru Besar',
            intitusi: 'Universitas Indonesia',
            fakultas: 'Fakultas Ekonomi dan Bisnis',
            prodi: 'Manajemen',
            username: 'herman_jy',
            password: 'pass@Herman05',
        },
        {
            id: 6,
            foto: 'https://placehold.co/600x400?text=R06',
            nik: '198807072012012002',
            nama: 'Eka Wijaya, S.E., M.Si.',
            email: 'eka.wijaya@unpad.ac.id',
            noHp: '081234567806',
            jafung: 'Lektor',
            intitusi: 'Universitas Padjadjaran',
            fakultas: 'Fakultas Ilmu Sosial dan Ilmu Politik',
            prodi: 'Administrasi Publik',
            username: 'eka_wj',
            password: 'pass@Eka06',
        },
        {
            id: 7,
            foto: 'https://placehold.co/600x400?text=R07',
            nik: '197402142001051004',
            nama: 'Dr. Joko Susilo, M.Kom.',
            email: 'joko.susilo@upn.ac.id',
            noHp: '081234567807',
            jafung: 'Lektor Kepala',
            intitusi: 'UPN "Veteran" Jawa Timur',
            fakultas: 'Fakultas Ilmu Komputer',
            prodi: 'Sistem Informasi',
            username: 'joko_ss',
            password: 'pass@Joko07',
        },
        {
            id: 8,
            foto: 'https://placehold.co/600x400?text=R08',
            nik: '199204182017032015',
            nama: 'Fina Az Zahra, M.Farm.',
            email: 'fina.zahra@unhas.ac.id',
            noHp: '081234567808',
            jafung: 'Asisten Ahli',
            intitusi: 'Universitas Hasanuddin',
            fakultas: 'Fakultas Farmasi',
            prodi: 'Farmasi Klinis',
            username: 'fina_az',
            password: 'pass@Fina08',
        },
        {
            id: 9,
            foto: 'https://placehold.co/600x400?text=R09',
            nik: '197109302000081006',
            nama: 'Dr. Ganjar Pranowo, M.Sc.',
            email: 'ganjar.pranowo@undip.ac.id',
            noHp: '081234567809',
            jafung: 'Lektor Kepala',
            intitusi: 'Universitas Diponegoro',
            fakultas: 'Fakultas Peternakan dan Pertanian',
            prodi: 'Agroteknologi',
            username: 'ganjar_pr',
            password: 'pass@Ganjar09',
        },
        {
            id: 10,
            foto: 'https://placehold.co/600x400?text=R10',
            nik: '198312052008022008',
            nama: 'Hesti Lestari, M.I.Kom.',
            email: 'hesti.lestari@unair.ac.id',
            noHp: '081234567810',
            jafung: 'Lektor',
            intitusi: 'Universitas Airlangga',
            fakultas: 'Fakultas Ilmu Budaya',
            prodi: 'Ilmu Komunikasi',
            username: 'hesti_lt',
            password: 'pass@Hesti10',
        },
        {
            id: 11,
            foto: 'https://placehold.co/600x400?text=R11',
            nik: '197606202003071001',
            nama: 'Iwan Darmawan, S.T., M.T.',
            email: 'iwan.darmawan@its.ac.id',
            noHp: '081234567811',
            jafung: 'Lektor Kepala',
            intitusi: 'Institut Teknologi Sepuluh Nopember',
            fakultas: 'Fakultas Teknologi Industri dan Rekayasa Sistem',
            prodi: 'Teknik Mesin',
            username: 'iwan_dw',
            password: 'pass@Iwan11',
        },
        {
            id: 12,
            foto: 'https://placehold.co/600x400?text=R12',
            nik: '199503152020102020',
            nama: 'Dr. Kartika Sari, M.Gizi.',
            email: 'kartika.sari@ub.ac.id',
            noHp: '081234567812',
            jafung: 'Asisten Ahli',
            intitusi: 'Universitas Brawijaya',
            fakultas: 'Fakultas Kedokteran',
            prodi: 'Ilmu Gizi',
            username: 'kartika_sr',
            password: 'pass@Kartika12',
        },
        {
            id: 13,
            foto: 'https://placehold.co/600x400?text=R13',
            nik: '196808081998041005',
            nama: 'Prof. Lukman Hakim, Sp.PD.',
            email: 'lukman.hakim@ui.ac.id',
            noHp: '081234567813',
            jafung: 'Guru Besar',
            intitusi: 'Universitas Indonesia',
            fakultas: 'Fakultas Kedokteran',
            prodi: 'Penyakit Dalam',
            username: 'lukman_hk',
            password: 'pass@Lukman13',
        },
        {
            id: 14,
            foto: 'https://placehold.co/600x400?text=R14',
            nik: '198701232013052009',
            nama: 'Mega Puspita, M.Ak.',
            email: 'mega.puspita@unpad.ac.id',
            noHp: '081234567814',
            jafung: 'Lektor',
            intitusi: 'Universitas Padjadjaran',
            fakultas: 'Fakultas Ekonomi dan Bisnis',
            prodi: 'Akuntansi',
            username: 'mega_pt',
            password: 'pass@Mega14',
        },
        {
            id: 15,
            foto: 'https://placehold.co/600x400?text=R15',
            nik: '197911112006031002',
            nama: 'Dr. Nanda Pratama, M.Sc.',
            email: 'nanda.pratama@undip.ac.id',
            noHp: '081234567815',
            jafung: 'Lektor Kepala',
            intitusi: 'Universitas Diponegoro',
            fakultas: 'Fakultas Sains dan Matematika',
            prodi: 'Fisika',
            username: 'nanda_pr',
            password: 'pass@Nanda15',
        },
        {
            id: 16,
            foto: 'https://placehold.co/600x400?text=R16',
            nik: '199102282016082018',
            nama: 'Oscar Darmawan, M.A.',
            email: 'oscar.darmawan@ugm.ac.id',
            noHp: '081234567816',
            jafung: 'Asisten Ahli',
            intitusi: 'Universitas Gadjah Mada',
            fakultas: 'Fakultas Ilmu Budaya',
            prodi: 'Sastra Inggris',
            username: 'oscar_dw',
            password: 'pass@Oscar16',
        },
        {
            id: 17,
            foto: 'https://placehold.co/600x400?text=R17',
            nik: '197210102001112004',
            nama: 'Puspa Sari, M.Psi.',
            email: 'puspa.sari@unair.ac.id',
            noHp: '081234567817',
            jafung: 'Lektor Kepala',
            intitusi: 'Universitas Airlangga',
            fakultas: 'Fakultas Psikologi',
            prodi: 'Psikologi Klinis',
            username: 'puspa_sr',
            password: 'pass@Puspa17',
        },
        {
            id: 18,
            foto: 'https://placehold.co/600x400?text=R18',
            nik: '199309052018041021',
            nama: 'Qiran Maulana, S.H., M.H.',
            email: 'qiran.maulana@ui.ac.id',
            noHp: '081234567818',
            jafung: 'Asisten Ahli',
            intitusi: 'Universitas Indonesia',
            fakultas: 'Fakultas Hukum',
            prodi: 'Hukum Pidana',
            username: 'qiran_ml',
            password: 'pass@Qiran18',
        },
        {
            id: 19,
            foto: 'https://placehold.co/600x400?text=R19',
            nik: '196704041997011003',
            nama: 'Prof. Rudi Hartono, Ph.D.',
            email: 'rudi.hartono@itb.ac.id',
            noHp: '081234567819',
            jafung: 'Guru Besar',
            intitusi: 'Institut Teknologi Bandung',
            fakultas: 'Fakultas Teknologi Industri',
            prodi: 'Teknik Kimia',
            username: 'rudi_ht',
            password: 'pass@Rudi19',
        },
        {
            id: 20,
            foto: 'https://placehold.co/600x400?text=R20',
            nik: '198106172007052007',
            nama: 'Dr. Sari Mulia, Ph.D.',
            email: 'sari.mulia@ugm.ac.id',
            noHp: '081234567820',
            jafung: 'Lektor Kepala',
            intitusi: 'Universitas Gadjah Mada',
            fakultas: 'Fakultas Ilmu Komputer',
            prodi: 'Ilmu Komputer',
            username: 'sari_ml',
            password: 'pass@Sari20',
        },
        {
            id: 21,
            foto: 'https://placehold.co/600x400?text=R21',
            nik: '197508292002061005',
            nama: 'Dr. Taufik Hidayat, M.P.',
            email: 'taufik.hidayat@ub.ac.id',
            noHp: '081234567821',
            jafung: 'Lektor',
            intitusi: 'Universitas Brawijaya',
            fakultas: 'Fakultas Pertanian',
            prodi: 'Agronomi',
            username: 'taufik_hd',
            password: 'pass@Taufik21',
        },
        {
            id: 22,
            foto: 'https://placehold.co/600x400?text=R22',
            nik: '199411032019012022',
            nama: 'Umi Kalsum, M.Ag.',
            email: 'umi.kalsum@uin.ac.id',
            noHp: '081234567822',
            jafung: 'Asisten Ahli',
            intitusi: 'UIN Sunan Kalijaga',
            fakultas: 'Fakultas Syariah dan Hukum',
            prodi: 'Hukum Keluarga Islam',
            username: 'umi_kl',
            password: 'pass@Umi22',
        },
        {
            id: 23,
            foto: 'https://placehold.co/600x400?text=R23',
            nik: '196901281999021008',
            nama: 'Prof. Vino Adrianto, M.Sn.',
            email: 'vino.adrianto@isi-yk.ac.id',
            noHp: '081234567823',
            jafung: 'Guru Besar',
            intitusi: 'Institut Seni Indonesia Yogyakarta',
            fakultas: 'Fakultas Seni Rupa',
            prodi: 'Kriya Seni',
            username: 'vino_ad',
            password: 'pass@Vino23',
        },
        {
            id: 24,
            foto: 'https://placehold.co/600x400?text=R24',
            nik: '198603072011042006',
            nama: 'Wulan Febriani, M.Hum.',
            email: 'wulan.febriani@unpad.ac.id',
            noHp: '081234567824',
            jafung: 'Lektor',
            intitusi: 'Universitas Padjadjaran',
            fakultas: 'Fakultas Ilmu Budaya',
            prodi: 'Sastra Indonesia',
            username: 'wulan_fb',
            password: 'pass@Wulan24',
        },
        {
            id: 25,
            foto: 'https://placehold.co/600x400?text=R25',
            nik: '197712122004091001',
            nama: 'Dr. Xena Amelia, M.E.',
            email: 'xena.amelia@usu.ac.id',
            noHp: '081234567825',
            jafung: 'Lektor Kepala',
            intitusi: 'Universitas Sumatera Utara',
            fakultas: 'Fakultas Ekonomi dan Bisnis',
            prodi: 'Ilmu Ekonomi',
            username: 'xena_am',
            password: 'pass@Xena25',
        },
        {
            id: 26,
            foto: 'https://placehold.co/600x400?text=R26',
            nik: '199605212021071023',
            nama: 'Yoga Pratama, S.Kom.',
            email: 'yoga.pratama@unair.ac.id',
            noHp: '081234567826',
            jafung: 'Tenaga Pengajar',
            intitusi: 'Universitas Airlangga',
            fakultas: 'Fakultas Sains dan Teknologi',
            prodi: 'Sistem Informasi',
            username: 'yoga_pr',
            password: 'pass@Yoga26',
        },
        {
            id: 27,
            foto: 'https://placehold.co/600x400?text=R27',
            nik: '198002022006102010',
            nama: 'Dr. Zulfa Hanum, M.Pd.',
            email: 'zulfa.hanum@unesa.ac.id',
            noHp: '081234567827',
            jafung: 'Lektor',
            intitusi: 'Universitas Negeri Surabaya',
            fakultas: 'Fakultas Ilmu Pendidikan',
            prodi: 'Teknologi Pendidikan',
            username: 'zulfa_hn',
            password: 'pass@Zulfa27',
        },
        {
            id: 28,
            foto: 'https://placehold.co/600x400?text=R28',
            nik: '197307192001031002',
            nama: 'Dr. Ari Wibowo, M.Sc.',
            email: 'ari.wibowo@its.ac.id',
            noHp: '081234567828',
            jafung: 'Lektor Kepala',
            intitusi: 'Institut Teknologi Sepuluh Nopember',
            fakultas: 'Fakultas Teknik Sipil, Perencanaan, dan Kebumian',
            prodi: 'Teknik Geomatika',
            username: 'ari_wb',
            password: 'pass@Ari28',
        },
        {
            id: 29,
            foto: 'https://placehold.co/600x400?text=R29',
            nik: '199709092022012025',
            nama: 'Bela Safitri, S.Psi.',
            email: 'bela.safitri@ugm.ac.id',
            noHp: '081234567829',
            jafung: 'Tenaga Pengajar',
            intitusi: 'Universitas Gadjah Mada',
            fakultas: 'Fakultas Psikologi',
            prodi: 'Psikologi Umum',
            username: 'bela_sf',
            password: 'pass@Bela29',
        },
        {
            id: 30,
            foto: 'https://placehold.co/600x400?text=R30',
            nik: '196604241996071004',
            nama: 'Prof. Doni Iskandar, M.Agr.',
            email: 'doni.iskandar@ipb.ac.id',
            noHp: '081234567830',
            jafung: 'Guru Besar',
            intitusi: 'Institut Pertanian Bogor',
            fakultas: 'Fakultas Pertanian',
            prodi: 'Ilmu Tanah',
            username: 'doni_is',
            password: 'pass@Doni30',
        },
    ];

    const { currentPage, perPage, handlePageChange, handlePerRowsChange } = useDataTablePagination(20);

    const columns: TableColumn<DataRowReviewer>[] = [
        {
            name: 'No',
            cell: (row, index) => (currentPage - 1) * perPage + index + 1,
            width: '2rem',
            style: {
                padding: '0px',
                justifyContent: 'center',
            },
        },
        {
            name: 'Foto',
            // selector: (row) => row.foto,
            cell: (row) => (
                <div className="h-40 w-60">
                    <img src={row.foto} alt="Foto Dosen" className="h-full object-contain" loading="lazy"></img>
                </div>
            ),
            // sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Nik',
            selector: (row) => row.nik,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Nama',
            selector: (row) => row.nama,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Email',
            selector: (row) => row.email,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'HP',
            selector: (row) => row.noHp,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Jafung',
            selector: (row) => row.jafung,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Institusi',
            selector: (row) => row.intitusi,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Fakultas',
            selector: (row) => row.fakultas,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Prodi',
            selector: (row) => row.prodi,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Username',
            selector: (row) => row.username,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Password',
            selector: (row) => row.password,
            sortable: true,
            wrap: true,
            center: true,
        },
        {
            name: 'Aksi',
            cell: () => (
                <div className="space-x-2">
                    <Button className="cursor-pointer bg-blue-600 hover:bg-blue-400">
                        <PenBox></PenBox>
                    </Button>
                    <Button className="cursor-pointer bg-red-600 hover:bg-red-400">
                        <Trash2></Trash2>
                    </Button>
                </div>
            ),
            wrap: true,
            center: true,
        },
    ];

    return (
        <DashLayout>
            <Head title="ASIPP | Data Dosen"></Head>
            <div className="bg-white p-6 shadow">
                <Button className="mb-2">Tambar Reviewer</Button>
                <h2 className="mb-2 text-xl font-semibold">Data Reviewer</h2>

                <Table columns={columns} data={data} handlePageChange={handlePageChange} handlePerRowsChange={handlePerRowsChange} />
            </div>
        </DashLayout>
    );
}
